// Pure geometry for the three involute constructions. NO DOM here — every function
// returns plain data (points, line segments, arc definitions, and a sampled polyline for
// the traced curve itself). renderConstruction.js is the only file that turns this into
// SVG.
//
// Layering (CLAUDE.md): leaf module, imports nothing. main.js calls build(params) for the
// active construction and hands the recipe to renderConstruction.js.
//
// Coordinate system: a fixed 200x140 drawing area (SVG viewBox units, the family default —
// see viewTransform.js's own note on why this topic doesn't need Topic 2.1's enlarged
// 240x190 canvas), origin top-left, y increases downward. Every construction computes its
// own geometry in a LOCAL MATH FRAME (origin at the most natural centre, y increases
// UPWARD like a textbook figure), then fitTransform() maps that frame into SVG space once,
// so every point — curve samples, base circle/polygon, tangent/normal — scales and centres
// together and nothing is fit against a stale, partially-computed bounding box.
//
// Every step in a recipe carries a `role`:
//   'given'  — the construction's starting element(s): the base circle/polygon
//   'move'   — an auxiliary construction line/arc, drawn WHILE building (never the answer)
//   'result' — the traced curve itself (or its final arc), and the tangent/normal built
//              from it
// renderConstruction.js maps role -> the DESIGN.md §2 construction-line token, same as
// every other topic in this track.
//
// ----------------------------------------------------------------------------
// THE GENERATOR — split out of `graphics_diploma_module_1_topic_2_1_roulettes` into this
// topic (ADR-080): an involute is generated by a taut string/line unwinding, a
// structurally different mechanism from a circle rolling on a base (that topic's own
// "Generator A"), so it never belonged in the same picker.
//
//   `involuteCirclePoint()` / `involutePolygonArcs()`: involute of a circle and involute
//   of a regular polygon. The circle case is a smooth closed-form parametric; the polygon
//   case isn't a smooth parametric at all, it's a chain of compass arcs of growing radius
//   (Example 7.7's own method), so it reuses the same `arc` step primitive every other
//   topic in this track already has, with no new geometry engine.
//
// The classical fact that the NORMAL to any roulette/involute at its traced point always
// passes through the curve's instantaneous point of contact with its base — `contactPoint`
// for a rolling circle, `involuteContactPoint()` here for a taut string — is why tangent/
// normal construction is one shared routine (`tangentNormalSteps()`), duplicated here from
// Topic 2.1 per RULES §1.4 (no shared library between topic folders).
// ----------------------------------------------------------------------------

const deg2rad = (d) => (d * Math.PI) / 180;

function dist(a, b) {
  return Math.hypot(b.x - a.x, b.y - a.y);
}

function angleOf(a, b) {
  return Math.atan2(b.y - a.y, b.x - a.x);
}

function pointAt(center, r, angleRad) {
  return { x: center.x + r * Math.cos(angleRad), y: center.y + r * Math.sin(angleRad) };
}

// ----------------------------------------------------------------------------
// Step builders — each returns a plain object renderConstruction.js knows how to draw
// ----------------------------------------------------------------------------

const P = (p, role, label, dx, dy) => ({ kind: 'point', role, p, label, dx, dy });
const L = (a, b, role, label) => ({ kind: 'line', role, a, b, label });
const CIRC = (center, radius, role) => ({ kind: 'circle', role, center, radius });
/** A sampled polyline — the only primitive that can draw an involute of a circle, since
 *  it is not a compass-constructible line/arc/circle. */
const CURVE = (points, role) => ({ kind: 'curve', role, points });
const arcMark = (center, radius, aimPoint, spanDeg = 60) => {
  const a = angleOf(center, aimPoint);
  const half = deg2rad(spanDeg / 2);
  return { kind: 'arc', role: 'move', center, radius, startAngle: a - half, endAngle: a + half };
};
const dim = (a, b, text, role, offset = 10) => ({ kind: 'dim', role, a, b, text, offset });

// ----------------------------------------------------------------------------
// The generator — involute of a circle / a regular polygon
// ----------------------------------------------------------------------------

/** Point on the involute of a circle of radius `r`, string unwound through `theta` radians. */
function involuteCirclePoint(theta, r) {
  return { x: r * (Math.cos(theta) + theta * Math.sin(theta)), y: r * (Math.sin(theta) - theta * Math.cos(theta)) };
}

/** The point of tangency on the circle (where the taut string currently leaves it) — the
 *  involute's own instantaneous contact point, same role as a rolling circle's contactPoint(). */
function involuteContactPoint(theta, r) {
  return { x: r * Math.cos(theta), y: r * Math.sin(theta) };
}

function sampleInvoluteCircle(r, thetaMax, n = 160) {
  const pts = [];
  for (let i = 0; i <= n; i++) pts.push(involuteCirclePoint((thetaMax * i) / n, r));
  return pts;
}

function sampleCircle(center, radius, n = 32) {
  const pts = [];
  for (let i = 0; i <= n; i++) pts.push(pointAt(center, radius, (2 * Math.PI * i) / n));
  return pts;
}

/**
 * Involute of a regular n-gon of side `side` (Example 7.7's method): n circular arcs of
 * radii side, 2*side, ..., n*side, each centred at a successive polygon vertex and swept
 * through the polygon's exterior angle (360/n degrees), chained end to start. Returns the
 * n arc steps plus the polygon's own vertex points — no smooth-curve engine needed, this
 * is fully compass-constructible with the existing `arc` primitive.
 */
function involutePolygonArcs(side, n) {
  const extAngle = (2 * Math.PI) / n;
  // Regular n-gon vertices, local frame, centred roughly under its own involute sweep.
  const verts = [];
  for (let i = 0; i < n; i++) verts.push(pointAt({ x: 0, y: 0 }, side / (2 * Math.sin(Math.PI / n)), (2 * Math.PI * i) / n - Math.PI / 2));

  const arcs = [];
  let current = verts[1]; // string starts flush along the edge V0->V1, free end at V1
  for (let i = 0; i < n; i++) {
    // Pivot order walks BACKWARD from V0 (V0, V(n-1), V(n-2), ..., V1), not forward —
    // verified numerically (scratchpad/verify_pivot_order.mjs): after the string sweeps
    // around V0 until flush with the incoming edge (the one ending at V0), the vertex
    // that edge started from — V(n-1) — is the next true pivot, not V1. The forward order
    // (V0,V1,V2,...) put every arc after the first at the wrong distance from its pivot
    // (e.g. a 120mm string pivoting at V1 when the free end was only 34.6mm away, not
    // 40mm), so consecutive arcs never actually met — confirmed by checking dist(pivot,
    // free end) against the intended radius exactly, not just eyeballing the render.
    const center = verts[i === 0 ? 0 : n - i];
    const radius = (i + 1) * side;
    const startAngle = angleOf(center, current);
    const endAngle = startAngle - extAngle; // spiral outward, consistent winding
    const next = pointAt(center, radius, endAngle);
    // RAW local-frame angles, deliberately NOT min/max'd here — fitTransform()'s SVG
    // mapping y-flips every point (y increases downward), which negates every angle
    // relative to a transformed centre. Reordering into min/max too early would throw
    // that sign away before the caller can correct for it, leaving the rendered arc
    // mirrored about its own centre and disconnected from the polygon's real vertices
    // (caught by numerically comparing arcPathD()'s rendered endpoints against the
    // tsv()-transformed vertex positions — they didn't coincide). Callers building the
    // SVG step negate (and only then min/max) startAngle/endAngle themselves.
    arcs.push({ kind: 'arc', role: i < n - 1 ? 'move' : 'result', center, radius, startAngle, endAngle });
    current = next;
  }
  return { arcs, verts, endPoint: current };
}

/** Local-frame arc angles -> the SVG-space angle pair arcPathD() actually needs, after
 *  fitTransform()'s y-flip (see involutePolygonArcs()'s note above). */
function svgArcAngles(a) {
  const s = -a.startAngle;
  const e = -a.endAngle;
  return { startAngle: Math.min(s, e), endAngle: Math.max(s, e) };
}

// ----------------------------------------------------------------------------
// Coordinate fitting — local math frame (y-up) -> SVG space (y-down), one shared helper
// ----------------------------------------------------------------------------

function boundsOfPoints(pts) {
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  for (const p of pts) {
    if (p.x < minX) minX = p.x;
    if (p.x > maxX) maxX = p.x;
    if (p.y < minY) minY = p.y;
    if (p.y > maxY) maxY = p.y;
  }
  return { minX, maxX, minY, maxY };
}

const PAD = 16; // svg units reserved for dim marks/labels beyond the geometry's own bbox

/** Fit a local math-frame bounding box into an SVG-space budget rect, once — every point
 *  in the recipe is transformed through the SAME toSvg(), so nothing can be scaled or
 *  centred independently of anything else. */
function fitTransform(bbox, budget, cap = 1.3) {
  const bw = Math.max(budget.w - PAD * 2, 1);
  const bh = Math.max(budget.h - PAD * 2, 1);
  const spanX = Math.max(bbox.maxX - bbox.minX, 1e-6);
  const spanY = Math.max(bbox.maxY - bbox.minY, 1e-6);
  const scale = Math.min(cap, bw / spanX, bh / spanY);
  const drawnW = spanX * scale;
  const drawnH = spanY * scale;
  const originX = budget.x + PAD + (bw - drawnW) / 2 - bbox.minX * scale;
  const originY = budget.y + PAD + (bh - drawnH) / 2 + bbox.maxY * scale;
  return { toSvg: (p) => ({ x: originX + p.x * scale, y: originY - p.y * scale }), scale };
}

const CANVAS = { w: 200, h: 140 };
const INVOLUTE_BUDGET = { x: 10, y: 10, w: 180, h: 120 };

// ----------------------------------------------------------------------------
// Shared tangent/normal construction — duplicated from Topic 2.1 (RULES §1.4) — the
// classical fact that an involute's normal at any point passes through the curve's
// instantaneous point of contact with the shape it unwinds from.
// ----------------------------------------------------------------------------

/**
 * @param {{x:number,y:number}} M  the traced point (local frame)
 * @param {{x:number,y:number}} C  the instantaneous contact point (local frame) — for the
 *   circle case, a new point the string leaves at; for the polygon case, the arc's own
 *   pivot vertex, already drawn/labelled as a 'given' point
 * @param {number} reach  how far the drawn tangent/normal segments extend past M/C
 * @param {boolean} showClassicalArc  unused by any construction in this topic — kept for
 *   parity with Topic 2.1's copy of this routine, which the cycloid construction there uses.
 * @param {{x:number,y:number}} [rollCentre]  required when showClassicalArc is true
 * @param {boolean} [drawContactPoint=true]  false for the polygon constructions, whose
 *   pivot vertex is already drawn/labelled as a 'given' point (A/B/C/D) — redrawing it
 *   here would duplicate that label on the exact same point.
 */
function tangentNormalSteps(M, C, reach, showClassicalArc, rollCentre, drawContactPoint = true) {
  const steps = [];
  if (showClassicalArc && rollCentre) {
    const r = dist(M, rollCentre);
    steps.push(arcMark(M, r, rollCentre, 50));
    steps.push(P(rollCentre, 'move', 'N'));
    steps.push(L(rollCentre, C, 'move'));
  }
  const normalAngle = angleOf(C, M);
  const nEnd = pointAt(M, reach * 0.4, normalAngle);
  steps.push(L(C, nEnd, 'result'));
  // C and M can land close together (e.g. involute-of-circle near small unwind angles) —
  // opposite-corner label offsets (C down-left, M's own default up-right) keep both
  // legible instead of stacking on top of each other.
  if (drawContactPoint) steps.push(P(C, 'result', 'C', -9, 5));
  const tangentAngle = normalAngle + Math.PI / 2;
  const t1 = pointAt(M, reach, tangentAngle);
  const t2 = pointAt(M, reach, tangentAngle + Math.PI);
  steps.push(L(t1, t2, 'result'), P(M, 'result', 'M'));
  return steps;
}

// ----------------------------------------------------------------------------
// The three constructions
// ----------------------------------------------------------------------------

/** @typedef {{key:string,label:string,unit:string,min:number,max:number,step:number,default:number}} ParamSpec */

/**
 * @typedef {Object} ConstructionDef
 * @property {string} id
 * @property {string} label
 * @property {string} shortLabel
 * @property {string} principle
 * @property {ParamSpec[]} given
 * @property {(params:Record<string,number>) => {steps:Array, resultText:string, invalid?:string}} build
 */

const THETA_PARAM = { key: 'theta', label: 'Roll angle', unit: '°', min: 0, max: 360, step: 5, default: 360 };

/** @type {ConstructionDef[]} */
export const CONSTRUCTIONS = [
  {
    id: 'involute-circle',
    label: 'Involute of a Circle',
    shortLabel: 'Involute (Circle)',
    principle: 'A point on a taut string unwound from a circle traces its involute; the string is always tangent to the circle, so the string itself IS the normal to the curve at the traced point.',
    given: [
      { key: 'diameter', label: 'Circle diameter', unit: 'mm', min: 30, max: 60, step: 5, default: 40 },
      THETA_PARAM,
    ],
    build({ diameter, theta }) {
      const r = diameter / 2;
      const thetaMax = 2 * Math.PI;
      const clampedDeg = Math.max(0, Math.min(360, theta));
      const fullPts = sampleInvoluteCircle(r, thetaMax, 160);
      const bbox = boundsOfPoints([...fullPts, ...sampleCircle({ x: 0, y: 0 }, r, 24)]);
      const { toSvg, scale } = fitTransform(bbox, INVOLUTE_BUDGET);
      const tsv = toSvg;

      const givenSteps = [
        CIRC(tsv({ x: 0, y: 0 }), r * scale, 'given'),
        P(tsv({ x: 0, y: 0 }), 'given', 'O'),
        dim(tsv({ x: -r, y: 0 }), tsv({ x: r, y: 0 }), `⌀ ${diameter} mm`, 'given', -14),
      ];

      /** The "how it got there" phase: the traced string OC itself, rotating and
       *  lengthening as it unwinds — that IS the rolling motion for an involute, so no
       *  separate spoke is needed. */
      function rollStepsAt(atDeg) {
        const at = deg2rad(Math.max(0, Math.min(360, atDeg)));
        const steps = [];
        const tracedPts = sampleInvoluteCircle(r, at, Math.max(8, Math.round(160 * (at / thetaMax))));
        if (tracedPts.length >= 2) steps.push(CURVE(tracedPts.map(tsv), 'result'));
        const M = involuteCirclePoint(at, r);
        const C = involuteContactPoint(at, r);
        steps.push(L(tsv(C), tsv(M), 'move'));
        steps.push(P(tsv(M), 'move'));
        return steps;
      }

      function tangentStepsAt(atDeg) {
        const at = deg2rad(Math.max(0, Math.min(360, atDeg)));
        const M = involuteCirclePoint(at, r);
        const C = involuteContactPoint(at, r);
        const reachSvg = r * 1.3 * scale;
        return tangentNormalSteps(tsv(M), tsv(C), reachSvg, false);
      }

      const steps = [...givenSteps, ...rollStepsAt(clampedDeg), ...tangentStepsAt(clampedDeg)];
      return {
        steps,
        resultText: `Involute traced through ${clampedDeg.toFixed(0)}° of unwind — the string OC is both the tangent-defining radius and the normal at M.`,
        animateRoll: { toDeg: clampedDeg, givenSteps, rollStepsAt, tangentStepsAt },
      };
    },
  },

  {
    id: 'involute-triangle',
    label: 'Involute of a Triangle',
    shortLabel: 'Involute (Triangle)',
    principle: 'Unwinding a taut string from a polygon happens one straight side at a time — each side sweeps a circular arc whose radius grows by that side’s length, centred on the vertex just left behind.',
    given: [{ key: 'side', label: 'Triangle side', unit: 'mm', min: 15, max: 40, step: 5, default: 20 }],
    build({ side }) {
      const { arcs, verts, endPoint } = involutePolygonArcs(side, 3);
      const bbox = boundsOfPoints([...verts, endPoint, ...arcs.flatMap((a) => sampleCircle(a.center, a.radius, 24))]);
      const { toSvg, scale } = fitTransform(bbox, INVOLUTE_BUDGET);
      const tsv = toSvg;
      const labels = ['A', 'B', 'C'];
      const steps = [];
      for (let i = 0; i < verts.length; i++) {
        steps.push(P(tsv(verts[i]), 'given', labels[i]));
        steps.push(L(tsv(verts[i]), tsv(verts[(i + 1) % verts.length]), 'given'));
      }
      for (const a of arcs) {
        const { startAngle, endAngle } = svgArcAngles(a);
        steps.push({ kind: 'arc', role: a.role, center: tsv(a.center), radius: a.radius * scale, startAngle, endAngle });
      }
      steps.push(P(tsv(endPoint), 'result', 'P'));

      // Tangent/normal at the midpoint of the third segment (the Problem Library's own
      // stated target: "the arc of radius 3×side, its midpoint") — the pivot vertex for
      // that arc is C (already drawn/labelled above as a 'given' point).
      const third = arcs[2];
      const midLocal = (third.startAngle + third.endAngle) / 2;
      const M = pointAt(third.center, third.radius, midLocal);
      const reachSvg = side * 1.3 * scale;
      steps.push(...tangentNormalSteps(tsv(M), tsv(third.center), reachSvg, false, undefined, false));

      return { steps, resultText: `Involute of an equilateral triangle, side ${side} mm — 3 arcs of radius ${side}, ${2 * side}, ${3 * side} mm; tangent/normal at the midpoint of the third arc.` };
    },
  },

  {
    id: 'involute-square',
    label: 'Involute of a Square',
    shortLabel: 'Involute (Square)',
    principle: 'The same one-side-at-a-time unwinding as the triangle, now around a fourth vertex — four arcs of radius side, 2×side, 3×side, 4×side.',
    given: [{ key: 'side', label: 'Square side', unit: 'mm', min: 15, max: 30, step: 5, default: 15 }],
    build({ side }) {
      const { arcs, verts, endPoint } = involutePolygonArcs(side, 4);
      const bbox = boundsOfPoints([...verts, endPoint, ...arcs.flatMap((a) => sampleCircle(a.center, a.radius, 24))]);
      const { toSvg, scale } = fitTransform(bbox, INVOLUTE_BUDGET);
      const tsv = toSvg;
      const labels = ['A', 'B', 'C', 'D'];
      const steps = [];
      for (let i = 0; i < verts.length; i++) {
        steps.push(P(tsv(verts[i]), 'given', labels[i]));
        steps.push(L(tsv(verts[i]), tsv(verts[(i + 1) % verts.length]), 'given'));
      }
      for (const a of arcs) {
        const { startAngle, endAngle } = svgArcAngles(a);
        steps.push({ kind: 'arc', role: a.role, center: tsv(a.center), radius: a.radius * scale, startAngle, endAngle });
      }
      steps.push(P(tsv(endPoint), 'result', 'P'));

      // Tangent/normal at the midpoint of the third segment (the Problem Library's own
      // stated target: "the arc of radius 3×side, its midpoint") — the pivot vertex for
      // that arc is C (already drawn/labelled above as a 'given' point).
      const third = arcs[2];
      const midLocal = (third.startAngle + third.endAngle) / 2;
      const M = pointAt(third.center, third.radius, midLocal);
      const reachSvg = side * 1.3 * scale;
      steps.push(...tangentNormalSteps(tsv(M), tsv(third.center), reachSvg, false, undefined, false));

      return { steps, resultText: `Involute of a square, side ${side} mm — 4 arcs of radius ${side}, ${2 * side}, ${3 * side}, ${4 * side} mm; tangent/normal at the midpoint of the third arc.` };
    },
  },
];

export const findConstruction = (id) => CONSTRUCTIONS.find((c) => c.id === id) ?? CONSTRUCTIONS[0];

export const __internal = { CANVAS };
